Fixed NoClassDefFoundError caused by latest Adventure-platform snapshot. (#4446)
* Bumped adventure versions

* Added Unit Test to ensure Adventure being set up correctly